name: GitHub Actions Demo

on:
  release:
    types:
      - published
    branches:
      - main
      
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        if: contains(env.GITHUB_REF, 'refs/tags/')
        run: |
          echo env.GITHUB_REF
          echo "yes it contains"
