name: GitHub Actions Demo

on:
  release:
    types:
      - published
    branches:
      - main
      
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        run: |
          echo "$GITHUB_REF"
