name: GitHub Actions Demo

on:
  release:
    types:
      - published
    branches:
      - main
      
jobs:
  hello:
    if: ${{ contains(env.GITHUB_REF, 'refs/tags/') }} 
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        run: |
          echo "yes it contains"
          echo $GITHUB_REF
